apiVersion: v1
kind: Service
metadata:
  name: k-3
  labels:
    app: kafka-3
    service: kafka
    broker_id: "3"
  namespace: acp-system
spec:
  # clusterIP: 10.200.10.33
  # type: ClusterIP
  clusterIP: 10.3.0.222
  ports:
    - name: broker
      port: 9092
  selector:
    app: kafka-3
    broker_id: "3"
