apiVersion: v1
kind: Service
metadata:
  name: k-2
  namespace: acp-system
  labels:
    app: kafka-2
    service: kafka
    broker_id: "2"
spec:
  # clusterIP: 10.200.10.32
  # type: ClusterIP
  clusterIP: 10.3.0.221
  ports:
    - name: broker
      port: 9092
  selector:
    app: kafka-2
    broker_id: "2"
