apiVersion: v1
kind: Service
metadata:
  name: k-1
  namespace: acp-system
  labels:
    app: kafka-1
    service: kafka
    broker_id: "1"
spec:
  # type: ClusterIP
  clusterIP: 10.3.0.220
  ports:
    - name: broker
      port: 9092
  selector:
    app: kafka-1
    broker_id: "1"
