apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller-3
  namespace: acp-system
  labels:
    name: kafka-3
    broker_id: "3"
spec:
  replicas: 1
  selector:
    app: kafka-3
    broker_id: "3"
  template:
    metadata:
      labels:
        app: kafka-3
        broker_id: "3"
        service: kafka
    spec:
      containers:
        - name: k-3
          image: quay.io/ukhomeofficedigital/kafka:v0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "3"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              valueFrom:
               fieldRef:
                 fieldPath: status.podIP
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data
