kind: ReplicationController
apiVersion: v1
metadata:
  name: mon-ae-clientstats-streaming
  namespace: central
  labels:
    appid: 6507f6d3-6b1e-4de2-b619-1c98564121d0
    groupid: DEFAULT
    version: 1.3.0-2
spec:
  replicas: 1
  selector:
    component: mon-ae-clientstats-streaming
    appid: 6507f6d3-6b1e-4de2-b619-1c98564121d0
    groupid: DEFAULT
    version: 1.3.0-2
  template:
    metadata:
      labels:
        component: mon-ae-clientstats-streaming
        appid: 6507f6d3-6b1e-4de2-b619-1c98564121d0
        groupid: DEFAULT
        version: 1.3.0-2
    spec:
      volumes:
      - name: mon-clientstats
        configMap:
          name: mon-ae-clientstats-streaming-config
          items:
            - key: clientstats.conf
              path: clientstats.conf
      - name: runtimes
        secret:
          secretName: central-secrets
      containers:
        - name: mon-ae-clientstats-aggregator
          image: quay.io/arubadevops/mon-ae-clientstats-aggregator:1.3.0-2
          args:
            - streaming
          volumeMounts:
            - name: mon-clientstats
              mountPath: /etc/spark-apps
              readOnly: true
            - name: runtimes
              mountPath: /etc/central_secrets
              readOnly: true
          env:
            - name: RUNTIME_CONF
              value: /etc/central_secrets/runtime.conf
            - name: KAFKA_BROKERS
              value: "10.3.0.220:9092,10.3.0.221:9092,10.3.0.222:9092"
            - name: ZOOKEEPER_SERVERS
              value: "zoo1:2181"
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
      imagePullSecrets:
        - name: quay.io
